name: Release CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: echo info
        run: 'https://javadoc.jitpack.io/com/github/mcxinyu/ScheduleTimeRuler/${{GITHUB_REF/refs\/tags\}}/ScheduleTimeRuler-${{env.GITHUB_REF_NAME}}.pom'
#      - name: Call JitPack
#        uses: fjogeleit/http-request-action@v1.5.0
#        with:
#          url: 'https://javadoc.jitpack.io/com/github/mcxinyu/ScheduleTimeRuler/${{github.ref_type}}/ScheduleTimeRuler-${{github.ref_type}}.pom'
#          method: 'GET'
#          timeout: 20000
