name: Release CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: echo info
        run: echo 'https://jitpack.io/com/github/mcxinyu/ScheduleTimeRuler/${{github.ref_name}}/ScheduleTimeRuler-${{github.ref_name}}.pom'
      - name: Call JitPack
        uses: fjogeleit/http-request-action@v1.5.0
        id: JitPack
        with:
#          url: 'https://jitpack.io/com/github/mcxinyu/ScheduleTimeRuler/${{github.ref_name}}/ScheduleTimeRuler-${{github.ref_name}}.pom'
          url: 'https://jitpack.io/com/github/mcxinyu/ScheduleTimeRuler/2020.1.7.1104/ScheduleTimeRuler-2020.1.7.1104.pom'
          method: 'GET'
          ignoreStatusCodes: 408
#      - uses: CamiloGarciaLaRotta/watermelon-http-client@v1
#        id: JitPack
#        with:
#          url: 'https://jitpack.io/com/github/mcxinyu/ScheduleTimeRuler/2020.1.7.1104/ScheduleTimeRuler-2020.1.7.1104.pom'
#          fail_fast: true
      - name: Show Response
        run: echo ${{ steps.JitPack.outputs.response }}
